Changes to Repository Name
explore-dev/demo-ts pull request #47
Opened 2020-06-09 14:11 UTC by marcelosousa

2020-09-07 09:28 UTC, Xavier-explore-dev commented on src/models/repository.ts
> +    first_name: string;
This should be called name.

2020-10-20 16:29 UTC, Xavier-explore-dev approved these changes

2020-10-20 16:30 UTC, Xavier-explore-dev reviewed
comment

2020-10-20 16:30 UTC, Xavier-explore-dev reviewed
comment 2

2020-10-20 16:31 UTC, Xavier-explore-dev requested changes
change

2020-10-20 16:37 UTC, Xavier-explore-dev approved these changes

2020-10-20 16:37 UTC, Xavier-explore-dev reviewed
qweqwe

2020-10-20 16:38 UTC, Xavier-explore-dev requested changes
asdqweqwe

2020-10-20 16:38 UTC, Xavier-explore-dev reviewed
qweqwasdasd

2020-10-20 16:39 UTC, Xavier-explore-dev approved these changes

2020-10-20 16:39 UTC, Xavier-explore-dev reviewed
qfasdqwe

2020-10-23 15:29 UTC, marcelosousa commented
This is a test comment

2020-10-23 15:39 UTC, marcelosousa commented
This is a test comment

2020-10-23 15:46 UTC, marcelosousa commented
This is a test comment

2020-10-28 13:35 UTC, marcelosousa commented
This is a test comment

2020-10-28 14:19 UTC, marcelosousa commented
This is a test comment

2020-10-28 14:20 UTC, marcelosousa commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
This is a test comment

2020-10-28 16:37 UTC, marcelosousa commented on README.md
> +
Pls rm new line

2020-10-28 16:43 UTC, marcelosousa commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
This is a test reply

2020-10-28 17:08 UTC, marcelosousa commented on src/components/GitHubController.tsx
> +    console.log('Say hello');
Change to `say bye`

2020-10-29 17:51 UTC, marcelosousa commented on README.md
> +
Test comment

2020-10-29 19:54 UTC, marcelosousa commented on README.md
> +
Remove this line

2020-10-29 19:56 UTC, marcelosousa commented
Comment test

2020-10-30 12:33 UTC, marcelosousa commented on README.md
> +* This is a demo project *
Test comment

2020-10-30 12:34 UTC, marcelosousa commented on README.md
> +* This is a demo project *
Reply

2020-10-30 16:43 UTC, marcelosousa commented on README.md
> +
Test comment

2020-11-17 18:10 UTC, ferreiratiago commented on src/components/GitHubController.tsx
>      const [repoHighlighted, setRepoHighlighted] = useState<Repository>();
Comment

2020-11-17 18:12 UTC, ferreiratiago commented on src/components/GitHubController.tsx
Comment

2020-12-03 16:35 UTC, marcelosousa commented on README.md
> +
Test comment

2020-12-14 15:09 UTC, marcelosousa commented on src/models/repository.ts
> +    full_name: Name;
I don't like this variable name.

2020-12-14 15:11 UTC, marcelosousa commented on src/components/RepositoryDetails/RepositoryDetails.tsx
> +            <p>Name: {repo.full_name.first_name}</p>
Test comment

2020-12-22 11:20 UTC, ferreiratiago commented on src/components/GitHubController.tsx
Reply 1

2020-12-22 11:20 UTC, ferreiratiago commented on src/components/GitHubController.tsx
Reply 2

2021-01-05 17:32 UTC, marcelosousa commented on src/components/RepositoryDetails/RepositoryDetails.tsx
> +            <p>Name: {repo.full_name.first_name}</p>
Another test comment

2021-01-06 16:36 UTC, marcelosousa commented on README.md
> +
Test reply

2021-01-26 18:59 UTC, closed without merging